### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3830-Fall2019/lab1-madisoncard#1]
@madisoncard 

Line 156 of your Rmd file should has:

^["Use the argument dpi = 96 inside include_graphics().↩"] 

and it should be

^["Use the argument `dpi = 96` inside `include_graphics()`."] 

The rest looks great.

**Comment by madisoncard** [comment]
@alanarnholt 

I fixed line 156 of the Rmd file.

**Comment by alanarnholt** [comment]
@madisoncard  Looks great! Closing issue.
